# Generated by Django 4.2.23 on 2025-08-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, help_text='Descrição do projeto em inglês (deixe vazio para usar a descrição padrão)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, help_text='Nome do projeto em inglês (deixe vazio para usar o título padrão)', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='available_for_work',
            field=models.BooleanField(default=True, help_text='Marque se você está procurando emprego/projetos'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='bio',
            field=models.TextField(help_text='Uma breve descrição sobre você e sua carreira'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(help_text='Seu email principal que aparecerá no portfólio', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='github_url',
            field=models.URLField(blank=True, help_text='URL do seu perfil no GitHub'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='URL do seu perfil no LinkedIn'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='location',
            field=models.CharField(help_text='Sua cidade/estado (ex: São Paulo, SP)', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, help_text='Seu telefone (formato livre, ex: (11) 99999-9999)', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='URL do seu perfil no Twitter'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data em que o projeto foi adicionado ao portfólio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Explique o que o projeto faz, qual problema resolve, etc.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Marque para exibir este projeto na página inicial'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link para o código no GitHub', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Screenshot ou imagem representativa do projeto', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordem de exibição (0 = primeiro, 1 = segundo, etc.)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='Link para acessar o projeto online (se houver)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('live', 'Online'), ('development', 'Desenvolvimento'), ('completed', 'Concluído')], default='completed', help_text='Situação atual do projeto', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.TextField(help_text='Tecnologias separadas por vírgula (ex: Python, Django, JavaScript, React)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Nome do seu projeto (ex: E-commerce de Roupas)', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data da última modificação do projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.IntegerField(help_text='Ano de conclusão do projeto (ex: 2024)'),
        ),
    ]
